TASK_AVAILABILITY = "availability"
TASK_PRESENCE = "presence"
TASK_BUSINESS = "business"
TASK_TALENT = "talent"
TASK_CONTENT = "content"
TASK_ADMIN = "admin"

NODE_SUPERVISOR = "main_supervisor"
NODE_CLASSIFIER = "platform_node"
NODE_AVAILABILITY = "availability_node"
NODE_PRESENCE = "presence_node"
NODE_FORMATTER = "format_response"
NODE_BUSINESS = "business_node"
NODE_TALENT = "talent_node"
NODE_CONTENT = "content_node"
NODE_ADMIN = "admin_node"

DECISION_CLASSIFY = "NECESITA_CLASIFICACION"
DECISION_COMPLETE = "COMPLETO"
