name: Build & Push to ECR

on:
  push:
    branches: [ main, rafa, ele, fran ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ROLE_ARN: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Decide tag by branch
        id: tag
        run: |
          case "${GITHUB_REF_NAME}" in
            main) TAG=main ;;
            rafa) TAG=rg   ;;
            ele)  TAG=er   ;;
            fran) TAG=ff   ;;
            *)    echo "Branch not mapped"; exit 1 ;;
          esac
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          docker build -t $ECR_REPOSITORY:${{ steps.tag.outputs.tag }} .

      - name: Push
        run: |
          docker tag $ECR_REPOSITORY:${{ steps.tag.outputs.tag }} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ steps.tag.outputs.tag }}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ steps.tag.outputs.tag }}