name: build-and-push

on:
  push:
    branches: [ main, rafa, ele, fran ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ROLE_ARN: ${{ secrets.AWS_ROLE_TO_ASSUME }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Now (UTC) for build metadata
        id: now
        run: echo "now=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$GITHUB_OUTPUT"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Decide image tag from branch
        id: tag
        run: |
          case "${GITHUB_REF_NAME}" in
            main) TAG=main ;;
            rafa) TAG=rg   ;;
            ele)  TAG=er   ;;
            fran) TAG=ff   ;;
            *) echo "Branch no mapeada: ${GITHUB_REF_NAME}"; exit 1 ;;
          esac
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      # --- CONSTRUCCIÓN CON BUILD-ARGS ---
      - name: Build image (with build metadata)
        run: |
          docker build \
            --build-arg BUILD_SHA="${GITHUB_SHA}" \
            --build-arg BUILD_REF="${GITHUB_REF_NAME}" \
            --build-arg BUILD_TIME="${{ steps.now.outputs.now }}" \
            -t "${{ env.ECR_REPOSITORY }}:${{ steps.tag.outputs.tag }}" .

      - name: Tag & push
        run: |
          IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.tag.outputs.tag }}"
          docker tag "${{ env.ECR_REPOSITORY }}:${{ steps.tag.outputs.tag }}" "$IMAGE_URI"
          docker push "$IMAGE_URI"

      - name: Show pushed digest (debug)
        run: |
          aws ecr describe-images \
            --repository-name "${{ env.ECR_REPOSITORY }}" \
            --image-ids imageTag=${{ steps.tag.outputs.tag }} \
            --query "imageDetails[0].imageDigest" --output text

      # --- VALIDACIÓN POST-DEPLOY EN APP RUNNER (OPCIONAL PERO ÚTIL) ---
      # Define estas 4 variables a nivel "Repository variables" en GitHub:
      #   APPRUNNER_URL_MAIN, APPRUNNER_URL_RAFA, APPRUNNER_URL_ELE, APPRUNNER_URL_FRAN
      - name: Pick service URL
        id: svc
        run: |
          case "${GITHUB_REF_NAME}" in
            main) url="${{ vars.APPRUNNER_URL_MAIN }}" ;;
            rafa) url="${{ vars.APPRUNNER_URL_RAFA }}" ;;
            ele)  url="${{ vars.APPRUNNER_URL_ELE }}" ;;
            fran) url="${{ vars.APPRUNNER_URL_FRAN }}" ;;
            *) echo "No URL for branch ${GITHUB_REF_NAME}"; exit 1 ;;
          esac
          echo "url=$url" >> "$GITHUB_OUTPUT"

      - name: Wait for healthy & correct version
        run: |
          url="${{ steps.svc.outputs.url }}"
          target_sha="${GITHUB_SHA}"
          echo "Waiting for ${url} to serve build ${target_sha} ..."
          for i in {1..45}; do
            code=$(curl -sS -o /dev/null -w "%{http_code}" "$url/healthz" || true)
            if [ "$code" = "200" ]; then
              got=$(curl -sS "$url/version" | tr -d '\r')
              echo "version: $got"
              # acepta tanto {"sha": "..."} como {"build": "..."} por compatibilidad
              sha=$(echo "$got" | jq -r '.sha // .build // empty' 2>/dev/null || true)
              if [ "$sha" = "$target_sha" ] || [ "$sha" = "${target_sha:0:7}" ]; then
                echo "✅ Healthy & correct image deployed"
                exit 0
              fi
            fi
            sleep 8
          done
          echo "❌ Timeout esperando deploy de ${target_sha} en ${url}"
          exit 1